name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '31 0 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    uses: famedly/github-workflows/.github/workflows/docker.yml@49401388492ed7fe3eeb13fbefacf68168e9bc64
    with:
      push: ${{ github.event_name != 'pull_request' }} # Always build, don't publish on pull requests
      image_name: rust-container
      tags: |
        type=raw,value=nightly
        type=raw,value=${{ vars.NIGHTLY_VERSION }}
      build_args: "[NIGHTLY_VERSION=${{ vars.NIGHTLY_VERSION }}]"
      registry: docker-oss.nexus.famedly.de
      registry_user: ${{ vars.NEXUS_REGISTRY_USER }}
    secrets: inherit
