name: Docker

on:
  schedule:
    - cron: "30 1 * * 1" # run every Monday at 01:30
  workflow_dispatch:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set_date:
    runs-on: ubuntu-latest
    outputs:
      date_today: ${{ steps.date_step.outputs.today }}
    steps:
      - id: date_step
        run: echo "today=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

  publish_release:
    if: github.ref == 'refs/heads/main'
    needs: set_date
    uses: famedly/github-workflows/.github/workflows/docker.yml@57b383862ba81dfa265bb33d492e2bbcbc96891d
    with:
      push: true
      image_name: rust-container
      tags: |
        type=raw,value=nightly
        type=raw,value=nightly-${{needs.set_date.outputs.date_today}}
      build_args: |
        NIGHTLY_VERSION_DATE=${{needs.set_date.outputs.date_today}}
      registry: registry.famedly.net/docker-oss
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets: inherit

  publish_dev:
    if: github.ref != 'refs/heads/main'
    needs: set_date
    uses: famedly/github-workflows/.github/workflows/docker.yml@57b383862ba81dfa265bb33d492e2bbcbc96891d
    with:
      push: true
      image_name: rust-container
      tags: |
        type=ref,event=branch,prefix=dev-
        type=ref,event=tag,prefix=dev-
        type=raw,event=pr,value=dev-${{ github.head_ref }}
        type=sha,prefix=dev-
      build_args: |
        NIGHTLY_VERSION_DATE=${{needs.set_date.outputs.date_today}}
      registry: registry.famedly.net/nightly
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets: inherit

  publish_ghcr_release:
    if: github.ref == 'refs/heads/main'
    needs: set_date
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@2ff7bc63ffa51414f77e9cbeea0d3297c1672d2e
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ghcr.io/${{ github.repository_owner }}/rust-container
          tags: |
            type=raw,value=nightly
            type=raw,value=nightly-${{needs.set_date.outputs.date_today}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@9e8d01178c767b734d2fef9a000ac2a2137f483f
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NIGHTLY_VERSION_DATE=${{needs.set_date.outputs.date_today}}

  publish_ghcr_dev:
    if: github.ref != 'refs/heads/main'
    needs: set_date
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@2ff7bc63ffa51414f77e9cbeea0d3297c1672d2e
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ghcr.io/${{ github.repository_owner }}/rust-container
          tags: |
            type=ref,event=branch,prefix=dev-
            type=ref,event=tag,prefix=dev-
            type=raw,event=pr,value=dev-${{ github.head_ref }}
            type=sha,prefix=dev-

      - name: Build and push Docker image
        uses: docker/build-push-action@9e8d01178c767b734d2fef9a000ac2a2137f483f
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NIGHTLY_VERSION_DATE=${{needs.set_date.outputs.date_today}}
